# ROS Noetic Template - Docker Compose Configuration
# This compose file demonstrates how to run the ROS template node
# roslaunch automatically starts roscore, so no separate rosmaster service needed

services:
  # Main template node (roslaunch automatically starts roscore)
  template_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:noetic
    pull_policy: never
    container_name: ros_template_node
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    command: >
      bash -c "roslaunch ros_template_node template_node.launch
               node_name:=template_node
               publish_rate:=2.0
               status_rate:=0.5"
    restart: unless-stopped
    volumes:
      # Mount logs directory for debugging
      - ./logs:/catkin_ws/logs
      # Optional: mount source code for development
      # - ./catkin_ws/src:/catkin_ws/src

volumes:
  logs:
    driver: local

# Usage Examples:
# 
# Start the ROS template node with Foxglove bridge:
#   docker-compose up
#
# View logs:
#   docker-compose logs -f template_node
#
# Interactive shell in the container:
#   docker-compose exec template_node bash
#
# Test ROS communication manually:
#   docker-compose exec template_node rostopic list
#   docker-compose exec template_node rostopic echo /template_output
#   docker-compose exec template_node rostopic pub -1 /template_input std_msgs/String "data: 'Test message'"
#
# Foxglove Visualization:
# - Access web-based Foxglove Studio at: https://studio.foxglove.dev
# - Connect to WebSocket: ws://localhost:8765